### ISSUE TITLE
how to build task 'emoji'

### ISSUE THREAD

**Issue by Nexword** [paginagmbh/redmine_emojibutton#12]
Hello! Can you help me, pls. I have same problem. #6  I have the directory **usr/share/redmine**. I created folder "plugins"  and cloned into the folder **usr/share/redmine/plugins** emoji plugin (git clone https://github.com/paginagmbh/redmine_emojibutton.git). 
In **usr/share/redmine/plugins/redmine_emojibutton/**
```
bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as
root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using gemoji 1.5.0
Using bundler 1.10.6 
```
In the plugin directory:
```
bundle show
Gems included by the bundle:
  * bundler (1.10.6)
  * gemoji (1.5.0)
```
Next step, i wrote **rake emoji** into **usr/share/redmine**
```
rake emoji

rake aborted!
cannot load such file -- tasks/emoji.rake
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `block in load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/share/redmine/plugins/redmine_emojibutton/lib/tasks/emoji.rake:1:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `block in load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/share/redmine/lib/tasks/redmine.rake:126:in `block in <top (required)>'
/usr/share/redmine/lib/tasks/redmine.rake:126:in `each'
/usr/share/redmine/lib/tasks/redmine.rake:126:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `block in load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:425:in `block in load_tasks'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:425:in `each'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:425:in `load_tasks'
/usr/lib/ruby/vendor_ruby/rails/application.rb:145:in `load_tasks'
/usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
/usr/share/redmine/Rakefile:7:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:589:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:89:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:88:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:72:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:70:in `run'
/usr/bin/rake:27:in `<main>'
```
What do you think about this error? What can go wrong? Maybe some gems missed?
```
gem list

*** LOCAL GEMS ***

bundler (1.10.6)
gemoji (1.5.0)
inifile (3.0.0)
lockfile (2.1.3)
net-ssh (2.9.2)
```
```
Environment:
  Redmine version              2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               MySQL
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_issue_control_panel    0.3.0
```

**Comment by tofi86** [comment]
I'm sorry, I cannot test and support with redmine 2.4. This plugin supports redmine 2.6.x and 3.0.x

The following is just some suggestions:

`gem list` in your redmine root(!) directory should list WAY MORE gems! Are you sure you're running `rake emoji` from the redmine root dir?

Also, if the `plugins` folder wasn't in place, `/usr/share/redmine/ is most likely not the redmine root dir! `plugins` folder is contained in a normal redmine installation.
