### ISSUE TITLE
Internal Server Error with redmine_persist_wfmt plugin

### ISSUE THREAD

**Issue by kimuraos** [paginagmbh/redmine_emojibutton#23]
This plugin is conflict with [redmine_persist_wfmt][] plugin.
The log shows as bellow:

```
Completed 500 Internal Server Error in 202ms (ActiveRecord: 43.1ms)
  
SystemStackError (stack level too deep):
  
app/models/setting.rb:275:in `text_formatting'
app/helpers/application_helper.rb:1591:in `wiki_helper'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_emojibutton/lib/emojibutton_helper_patch.rb:39:in `heads_for_wiki_formatter_with_redmine_emojibutton'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_emojibutton/lib/emojibutton_helper_patch.rb:39:in `heads_for_wiki_formatter_with_redmine_emojibutton'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_emojibutton/lib/emojibutton_helper_patch.rb:39:in `heads_for_wiki_formatter_with_redmine_emojibutton'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_emojibutton/lib/emojibutton_helper_patch.rb:39:in `heads_for_wiki_formatter_with_redmine_emojibutton'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
...
plugins/redmine_emojibutton/lib/emojibutton_helper_patch.rb:39:in `heads_for_wiki_formatter_with_redmine_emojibutton'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
plugins/redmine_emojibutton/lib/emojibutton_helper_patch.rb:39:in `heads_for_wiki_formatter_with_redmine_emojibutton'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:13:in `heads_for_wiki_formatter'
lib/redmine/wiki_formatting/markdown/helper.rb:23:in `wikitoolbar_for'
plugins/redmine_persist_wfmt/lib/patches/helper/markdown_helper_patch.rb:8:in `wikitoolbar_for'
app/views/wiki/edit.html.erb:62:in `block in _app_views_wiki_edit_html_erb___2485041404466169618_47445791144120'
app/views/wiki/edit.html.erb:5:in `_app_views_wiki_edit_html_erb___2485041404466169618_47445791144120'
plugins/redmine_wiki_extensions/lib/wiki_extensions_wiki_controller_patch.rb:31:in `render'
```

I'm not sure which is wrong.

[redmine_persist_wfmt]: https://www.redmine.org/plugins/redmine_persist_wfmt

**Comment by tofi86** [comment]
I'm afraid my Rails skills are too bad to know what the issue is here when both plugins are installed.

I asked the other maintainer for help in https://github.com/pinzolo/redmine_persist_wfmt/issues/18

**Comment by kimuraos** [comment]
ping
Why was the PR #25 closed without applying to `gemoji-4.0-native-emojis-no-images` branch?
[alexandermeindl's fork](https://github.com/alexandermeindl/redmine_emojibutton) has been removed.
